# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-09 08:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('aww', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 9, 8, 42, 7, 806741, tzinfo=utc)),
        ),
    ]
